### PR TITLE
Make MySQL go faster

### PR DESCRIPTION
**Pull request by rishi-freshbooks**
Inspired by: http://www.tocker.ca/2013/11/04/reducing-mysql-durability-for-testing.html

Since we don't care about durability in test envrionments, lets turn the knobs.

### CODE REVIEW

**Comment by wlonkly** [comment]
Makes sense for where we're using this now, but is this a good idea for our public, non-testing-specific docker-percona? Especially since the README.md has instructions for persisting data.

(i.e. are we going to use this later and be surprised by this change when our data isn't there, or is someone else?)

**Comment by rishi-freshbooks** [comment]
Rich makes a valid point; this configuration does not belong in a generic percona image.
hutchic / ddub thoughts on where this config could live for testing purposes?

**Comment by rishi-freshbooks** [comment]
These folks may have found a way: https://github.com/slobo/docker-mysql-reduced-durability/blob/master/5.5/etc/mysql/conf.d/reduced_durability.cnf

**Comment by rishi-freshbooks** [comment]
Closing, since we found a better place for this.

**Pull request closed without merging**
